[build]
  # 构建命令
  command = "npm install --include=dev && cd apps/web && npm install --include=dev && npx tsc --version && npm run build"
  
  # 发布目录
  publish = "apps/web/dist"
  
  # 函数目录
  functions = "apps/functions/dist"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "18.20.8"
  
  # npm 版本
  NPM_VERSION = "10.8.2"
  
  # 构建环境变量
  NODE_ENV = "production"
  
  # 跳过 Husky 安装
  HUSKY = "0"

[dev]
  # 开发服务器配置
  command = "cd apps/web && npm run dev"
  port = 3000
  publish = "apps/web/dist"
  functions = "apps/functions/src"

# 重定向规则
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 头部设置
[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    cache-control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    cache-control = "public, max-age=31536000"

# 环境变量（生产环境）
[context.production.environment]
  NODE_ENV = "production"

# 环境变量（预览环境）
[context.deploy-preview.environment]
  NODE_ENV = "staging"

# 环境变量（分支预览）
[context.branch-deploy.environment]
  NODE_ENV = "development"

[build]
  functions = "apps/functions"
